name: adw-gtk3-theme
base: core20 # the base snap is the execution environment for this snap
version: '1.0'
summary: adw-gtk3 snap port.
architectures:
  - build-on: amd64
    run-on: all
description: |
  adw-gtk3 theme is libadwaita theme for GTK3.
  Port based on the theme ports from Genadi Naydenov (gantonayde).
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

slots:
  gtk-3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/adw-gtk3
        - $SNAP/share/themes/adw-gtk3-dark
        
parts:
  # adw-gtk3 themes
  adw-gtk3-themes:
    after: [utils]
    plugin: nil
    source: https://github.com/lassekongo83/adw-gtk3/releases/download/v1.8/adw-gtk3v1-8.tar.xz
    override-build: |
        snapcraftctl build
        snapcraftctl set-version "$(git describe --tags 2>/dev/null || echo 1.0)"
        mkdir -p $SNAPCRAFT_PART_INSTALL/share/themes
        mv $SNAPCRAFT_PART_INSTALL/usr/share/themes/adw-* $SNAPCRAFT_PART_INSTALL/share/themes/
    stage:
      - share/themes/*/gtk-3*
      
  utils:
    plugin: dump
    source: utils
    prime:
      - -*
    build-packages:
      - try: [gtk-update-icon-cache]
      - else: [libgtk-3-bin]
